# Generated by Django 3.2.10 on 2022-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password_Reset',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(default='/media/user_default.png', null=True, upload_to='', verbose_name=''),
        ),
    ]
