# Generated by Django 3.2.10 on 2022-01-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
