# Generated by Django 3.2.10 on 2022-01-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_user_id',
            field=models.IntegerField(default=1),
        ),
    ]
