# Generated by Django 3.2.10 on 2022-01-14 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220113_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_resets',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 3, 11, 28, 121846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 3, 11, 28, 121464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='deleted_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 3, 11, 28, 121464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 3, 11, 28, 120464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 3, 11, 28, 120464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_user_id',
            field=models.IntegerField(default=1),
        ),
    ]
