# Generated by Django 3.2.10 on 2022-01-14 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220114_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_resets',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 6, 57, 45, 483516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 6, 57, 45, 483516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 6, 57, 45, 483516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 6, 57, 45, 483516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 6, 57, 45, 483516, tzinfo=utc)),
        ),
    ]
