# Generated by Django 3.2.10 on 2022-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='type',
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Admin'), ('u', 'User')], default='u', help_text='User Type', max_length=1),
        ),
    ]
