# Generated by Django 3.2.10 on 2022-01-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220117_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='status',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
