# Generated by Django 3.2.10 on 2022-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220118_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
