# Generated by Django 3.2.10 on 2022-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Admin'), ('1', 'User')], default='u', help_text='User Type', max_length=1),
        ),
    ]
